# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: We Blog
email: ofek@theofekfoundation.org
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.theofekfoundation.org" # the base hostname & protocol for your site
enforce_ssl: blog.theofekfoundation.org
mainurl: "https://www.theofekfoundation.org"
# twitter_username:
github_username: ofekih

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: default
      new-tab-redirect: true
      comments: true
      toc: true
